var Horoscopes = {
    'capricorn': "Intimidating Pluto remains in your Image House throughout 2016, giving you a decided edge on the competition. It should be easy for you to exude an air of calm control, even when you're feeling uncertain. If you want to win someone's heart, play the aggressor. When you ask for a date, propose a specific outing. Being prepared will make a terrific impression on the right person. Are you looking for work?\n\
    Dress for the job you want, not for the one you have. When you talk, think and behave like an accomplished person, success will find you. You may see some interesting career activity this year. On March 23rd, a Lunar Eclipse could see the sudden departure of an authority figure. You might be asked to replace this official, but be careful. This position could be more trouble than it is worth.\n\
    Another Lunar Eclipse on August 18th suggests that your company may experience financial difficulty. Fortunately, your job prospects will dramatically improve after September 10th. That's when expansive Jupiter will enter your Career Sector. Not only should it be easier to find your dream job, but you'll also be appreciated by the people who hire you. Saturn, your ruling planet, will be touring your Mystical Sector throughout 2016. This will give you an opportunity to review what is truly important in your life. Having more time for spiritual pursuits, uplifting relationships and meaningful work will take precedence over wealth and status.\n\
&copy; Kelli Fox and The Astrologer, Inc. To read more visit: <a href='http://new.theastrologer.com/2016-horoscope/'>http://new.theastrologer.com/2016-horoscope/</a>",

    'aquarius': "2016 invites you to keep your feet on the ground and think in terms of what is practical. That can be quite a challenge for you, Aquarius, since you are a born visionary. However, it's important to have a strong financial foundation from which to launch your ideas. Fortunately, generous Jupiter will be touring your Shared Resources Sector between January 1st and September 9th. Take this opportunity to apply for grants, loans and scholarships. You could receive a nice windfall from a wealthy foundation, easing the economic burdens of daily life.\n\
    On August 18th, a Lunar Eclipse will fall in your Image Sector, allowing you to embark on a more rewarding lifestyle. Keeping up with the Joneses may no longer seem important after this fateful date. Instead of working around the clock to pay the bills, you might choose to pursue a less demanding job. This new position could give you more time for the activities you really love. You might also be able to dress more simply and forgo expensive salon treatments. Intellectual pursuits will continue to bring you lots of pleasure.\n\
    That's because Uranus, your ruling planet, is continuing its tour of your Cerebral Sector. A writing project, challenging course or research job will be a source of tremendous highs and lows. Stick with this endeavor, because it's taking you to a higher level of success. You're sure to meet some influential people who can promote your work this year. Your impressive social circle comes courtesy of ambitious Saturn, which is moving through your Friendship Sector throughout 2016.\n\
&copy; Kelli Fox and The Astrologer, Inc. To read more visit: <a href='http://new.theastrologer.com/2016-horoscope/'>http://new.theastrologer.com/2016-horoscope/</a>",

    'pisces': "You could undergo a dramatic transformation this year, thanks to two eclipses that fall in Pisces. The first happens on March 8th, when a Solar Eclipse prompts you to change your appearance in some way. Whether you change your hairstyle, revamp your wardrobe, undergo a fitness regimen or get a cosmetic procedure is immaterial. The important thing is to alter your outward appearance to match your personality. Implementing changes in early March will be empowering. Six months later, on September 16th, a Lunar Eclipse will occur in Pisces, causing you to dispense with a role that no longer suits you.\n\
    Leaving a job that bothers your conscience is a distinct possibility. Embarking on a more rewarding profession is a distinct possibility, thanks to serious Saturn's journey through your Career Sector. Although it may be necessary to accept a low-level position as a means to gain experience, you'll be much happier with this change of pace. Opportunities involving travel, education and publishing are highly favored. If you'd like to work overseas, learning a foreign language will dramatically improve your job prospects. Whatever your plans, you will get tremendous support from your best friend, romantic partner or business associate.\n\
That's because benevolent Jupiter will be touring your Relationship Sector between January 1st and September 9th. You can rely on your nearest and dearest to offer help in all forms during the first eight months of the year. On September 10th, Jupiter will move into your Intimacy Sector. A close relationship could heat up during the last four months of the year.\n\
&copy; Kelli Fox and The Astrologer, Inc. To read more visit: <a href='http://new.theastrologer.com/2016-horoscope/'>http://new.theastrologer.com/2016-horoscope/</a>",

    'aries': "Beneficial Jupiter will be touring your Health and Well-being Sector until September 9th. This is an opportune time to get in shape, undergo a surgical procedure or recover from an illness. Follow your doctor's instructions to the letter or you won't get the full benefit of their expertise. There's a chance you'll have to alter your diet or rearrange your schedule to feel better. Although you'd rather do things the old way, you'll feel so much better when you make these few simple adjustments. Give yourself time to be uncomfortable while you undergo this transition.\n\
    After September 9th, you'll enjoy a surge of luck in the relationship department, thanks to Jupiter's entry to Libra. If you're single, you may meet someone special at a religious, cultural or educational gathering. Keep your eyes open for someone with gentle coloring who dresses well.. The potential for a lifetime of happiness is strong. If you already have a partner, this would be a wonderful time to renew your commitment to each other. Taking a romantic vacation or spending more time together is strongly advised.\n\
    You'll remain creative, vibrant and original throughout 2016, thanks to unique Uranus's tour of your Personal Sector. Don't bother to blend in with the crowd. You'll fare much better by proposing unusual ideas, breaking new ground and challenging the status quo. Pluto's tour of your Career Sector will trigger some standoffs with authority figures, but you'll be able to win them over, provided you are respectful.\n\
&copy; Kelli Fox and The Astrologer, Inc. To read more visit: <a href='http://new.theastrologer.com/2016-horoscope/'>http://new.theastrologer.com/2016-horoscope/</a>",

    'taurus': "Be alert during the weeks between April 29th and May 22nd, when Mercury, the planet of communication, moves through your Sun Sign. You might decide to alter your appearance in some way, upgrading your wardrobe or getting a new hairstyle. Keep your receipts and don't do anything too radical, as it's easy to change your mind under this transit. Still, this is a nice opportunity to challenge your assumptions about how you should lead your life. Jupiter, the planet of good fortune, continues to travel through your Romance and Creativity Sector until September 9th. Take this opportunity to develop your artistic talent.\n\
    If you've ever wanted to sell your handiwork, set your sights on this prolific period to do so. Adopting or conceiving a child is also possible under this transit, as is getting engaged or married. Once Jupiter moves into gracious Libra on September 10th, your good fortune will shift to health matters. Getting in shape, losing weight, recovering from an illness or getting treatment for a medical condition are among the possibilities. Pluto, the planet of transformation, will be touring your Personal Expansion Sector. If you want to change your life, you can do it through travel, study or spiritual exploration.\n\
    Writing can also have a profound effect on you. Becoming a novelist, screenwriter or playwright is entirely possible under this transit. Knowledge is power throughout 2016.\n\
&copy; Kelli Fox and The Astrologer, Inc. To read more visit: <a href='http://new.theastrologer.com/2016-horoscope/'>http://new.theastrologer.com/2016-horoscope/</a>",

    'gemini': "2016 may be a time of major transitions for you. Three eclipses are especially important to note. On March 8th, a Solar Eclipse in your Career Sector marks an exciting job opportunity. Make sure to apply for a position that sounds ideal, even if you think you lack the necessary experience. This could be your chance to land your dream job. On September 1st, a Solar Eclipse in your Domestic Sector could prompt you to make some changes to accommodate a relative; it might be necessary to relocate or rearrange your home.\n\
    Two weeks later, on September 16th, a Lunar Eclipse in your Career Sector might prompt you to change your professional priorities, cutting back on work in favor of more time with your nearest and dearest. Mercury, your ruling planet, will go retrograde in your Domestic Sector between August 31st and September 22nd. This will be a good time to reconsider the best living arrangement for you and your family. If you live alone, you may decide to combine households with a roommate to save money. Do you share the rent with a group of people?\n\
    It's possible you'll find your own place. If you own your house, it may be necessary to renovate or update a room. Be flexible and think in terms of what arrangement will serve you and your family best.\n\
&copy; Kelli Fox and The Astrologer, Inc. To read more visit: <a href='http://new.theastrologer.com/2016-horoscope/'>http://new.theastrologer.com/2016-horoscope/</a>",

    'cancer': "Pain could give way to pleasure in 2016. A difficult situation involving your family will come to a head on March 23rd, when a Lunar Eclipse falls in your Domestic Sector. You may find a good school for a child with special needs or arrange home health care for an elderly relative. You might decide your current living situation is untenable and you'll relocate. This break will be difficult but therapeutic. The fantastic news is that benevolent Jupiter will move into this same area of your chart on September 10th.\n\
    At that point, you'll find a wonderful living situation that seems too good to be true. Embrace this lucky turn of events with open arms. It's your reward for handling a volatile situation with grace, dignity and intelligence. Work will undergo a dramatic improvement, thanks to stable Saturn's tour of your Job Sector. Not only should you be able to land a steady position, but there also appears to be a great deal of growth potential here. With Uranus traveling through your Career Sector, you could suddenly get an impressive promotion.\n\
Being diligent and reliable will serve you well. Passionate Pluto continues its visit to your Relationship Sector, adding intensity to any intimate relationship. If you're looking for love, you could find it while attending a professional conference or business trip. Are you single? You may launch a successful business with your partner.\n\
&copy; Kelli Fox and The Astrologer, Inc. To read more visit: <a href='http://new.theastrologer.com/2016-horoscope/'>http://new.theastrologer.com/2016-horoscope/</a>",

    'leo': "2016 could be a tremendously lucrative year for you. That's because benevolent Jupiter will be touring your Earned Income Sector between January 1st and September 9th. There's a strong possibility you will land a job with a big salary. Getting a raise is another possibility. Selling an invention, book or song are other possibilities. A creative person like you, Leo, has tremendous potential for becoming wealthy through the fruits of your labor.\n\
By giving your talent the time and attention it deserves, you can emerge from this year with a much bigger bank account. Saturn, the planet of commitment, will be moving through your Knowledge Sector throughout the year. Any endeavors involving personal expansion are strongly favored. Traveling, studying and writing can both improve your financial standing and provide spiritual fulfillment. Take every opportunity to venture out of your comfort zone in 2016. You will gain a deeper appreciation of the world and learn some surprising things about yourself.\n\
    A Lunar Eclipse on August 18th could mark an interesting turning point in a close relationship. That's when your best friend, romantic partner or business associate could get a sudden opportunity to study abroad. This will require you both to make some changes to your relationship, but this shift will be beneficial if you keep fear and jealousy at bay. Encourage your nearest and dearest to take chances and realize their potential. You may be repaid tenfold.\n\
&copy; Kelli Fox and The Astrologer, Inc. To read more visit: <a href='http://new.theastrologer.com/2016-horoscope/'>http://new.theastrologer.com/2016-horoscope/</a>",

    'virgo': "It may be easy to get the recognition you desire this year, since expansive Jupiter will be touring your Image Sector. Commanding romantic attention could be a snap. If you have your own business, you'll find it easy to garner favorable publicity for our work. Are you in the performing arts? A role of a lifetime might be awarded to you during the first eight months of the year. Take advantage of this trend, since it is as rare as it is beneficial.\n\
    You may decide to revamp your image sometime between August 31st and September 22nd. That's when Mercury, your ruling planet, goes retrograde in Virgo. You could decide to become more aggressive in love. It's possible you will change the logo of your business or alter your appearance in some way. Whatever you decide, you should be pleased with the results. You'll get some help from the Solar Eclipse on September 1st.\n\
Be aware that your family may be uncomfortable with this transformation at first. They'll prefer the old you, but you'll be excited about the change. Domestic responsibilities will play a greater role in your life. You might decide to leave work to take care of a small child or elderly relative. Buying or selling a piece of property could be more challenging than you anticipated. It may be necessary to relocate for the sake of your career or that of your partner. Stay positive and be good to yourself.\n\
&copy; Kelli Fox and The Astrologer, Inc. To read more visit: <a href='http://new.theastrologer.com/2016-horoscope/'>http://new.theastrologer.com/2016-horoscope/</a>",

    'libra': "Recently, you've been working behind the scenes quite diligently. Although you're a social butterfly by nature, you'll continue to maintain a low profile for the first eight months of the year. Your love of solitude can be attributed to Jupiter's tour of your Privacy Sector. Instead of rubbing elbows with a wide array of people, you'll spend as much time as possible in seclusion. It will be a wonderful time for spiritually uplifting pursuits. Developing creative projects, communing with nature and connecting with your higher power can be very rewarding from January through September.\n\
    Pay careful attention to the days surrounding March 23rd. That's when a Lunar Eclipse will fall in your Image Sector. You may decide to abandon a lifestyle that no longer suits your needs. It's possible you'll abandon a stylish look for one that is simpler and easier to maintain. You might even change your name or present yourself as a different person from the past. Once September 9th arrives, expansive Jupiter will move into your Image Sector, allowing you to make a dramatic entrance into the spotlight.\n\
    People will be highly receptive to the new you. You'll become more outgoing and will resume your lively social life. It will be a great time to launch a business, go on auditions and play the dating game. This joyous trend will continue through next year soenjoy it!\n\
&copy; Kelli Fox and The Astrologer, Inc. To read more visit: <a href='http://new.theastrologer.com/2016-horoscope/'>http://new.theastrologer.com/2016-horoscope/</a>",

    'scorpio': "2016 is a time to wrap up loose ends. For the first eight months of the year, your friends will be encouraging you to leave a destructive situation behind. That's when benevolent Jupiter will be moving through your Friendship Sector. Lean on your nearest and dearest for support between January 1st and September 9th. With their support, you could summon the strength to end a job, relationship or habit that is no longer working for you. By September 10th, you'll feel much better about your life and take some time to cultivate your spiritual side.\n\
    Jupiter will be moving through your Mystical Sector. Being able to transcend mundane problems will be an enriching experience. The last four months of the year may not be terribly volatile, but they will be rewarding. It's entirely possible you will be turning your back on an unrewarding job. A Lunar Eclipse in your Career Sector on August 18th suggestions you may pull the plug on a professional position that is no longer working for you. Instead of being consumed by fear, you'll feel instantly gratified you put your happiness before a paycheck.\n\
    Finances may be a bit tight throughout the year, due to restrictive Saturn's journey through your Earned Income Sector. Fortunately, you're very resourceful and know how to thrive on a budget. Have faith in yourself and you'll make the most of this character building year.\n\
&copy; Kelli Fox and The Astrologer, Inc. To read more visit: <a href='http://new.theastrologer.com/2016-horoscope/'>http://new.theastrologer.com/2016-horoscope/</a>",

    'sagittarius': "Sober Saturn will be moving through your Image Sector throughout 2016. Your naturally ebullient personality could be a bit subdued, thanks to additional responsibilities being imposed on you. Instead of running from these challenges, rise to them. You'll gain the respect of both your peers and superiors by putting childish things away and assuming adult duties. A series of eclipses throughout the year will invite you to move out of your comfort zone. A Solar Eclipse on March 8th could prompt you to relocate to an area that is much more suited to your lifestyle.\n\
    If you don't own your place, you'll have a great opportunity to buy one. A generous relative or good bank loan can turn this dream into reality. On September 1st, a Solar Eclipse may trigger a career opportunity. Be aware this job will place great demands on your time. Although this position will be prestigious, it won't leave much opportunity for fun and games. Two weeks later, a Lunar Eclipse on September 16th could find you ending an emotional family matter that's draining your energy.\n\
    Stand up for yourself. Fortunately, expansive Jupiter will be helping you to achieve professional success. You should double your efforts at work between January 1st and September 9th. That's when you might reach heights you never dreamed possible. On September 10th, Jupiter will move into your Friendship Sector, giving you much needed support from your nearest and dearest.\n\
&copy; Kelli Fox and The Astrologer, Inc. To read more visit: <a href='http://new.theastrologer.com/2016-horoscope/'>http://new.theastrologer.com/2016-horoscope/</a>"
};